name: Update FPL snapshot

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 1 * * 2"   # ทุกวันอังคาร 01:00 UTC = 08:00 น. เวลาไทย (ICT)


permissions:
  contents: write               # ต้องมีสิทธิ์เขียนไฟล์กลับเข้ารีโป

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # ให้เห็นไฟล์/ประวัติครบ จะได้ commit ได้

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # ถ้าไฟล์สคริปต์อยู่ที่ scripts/build-fpl.mjs ตามที่ส่งไว้ ให้รันแบบนี้
      - name: Build latest FPL snapshot
        run: node scripts/build-fpl.mjs

      - name: Commit if changed
        run: |
          if git diff --quiet -- public/data/fpl_current.json; then
            echo "No changes in fpl_current.json"
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/data/fpl_current.json
          git commit -m "chore(data): refresh fpl_current.json [skip ci]"
          git push
