name: name: FPL Weekly (Single File)

on:
  schedule:
    # ทุกวันอังคาร 09:00 น. เวลาไทย (GitHub ใช้ UTC → 02:00)
    - cron: "0 2 * * 2"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate current snapshot
        run: node scripts/fpl_tuesday_single.mjs

      - name: Commit snapshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update FPL current snapshot (Tuesday run)"
          file_pattern: "public/data/fpl_current.json"


